### ISSUE TITLE
hello,I want to use your model to check whether my model is injected into the back door. However, there are some problems with some parameter settings

### ISSUE THREAD

**Issue by xiaolinjieer** [SSGAalto/prada-protecting-against-dnn-model-stealing-attacks#2]
Parameter load_location  in load_server() function_ Is the value of location the address of the training saved model Pt file? I saved a model file lenet.pt with lenet network, and I set Oracle in the main function The value of path is the address of: lenet,load_location :the address with location set to lenet.pt . it reports an error magic_ number = pickle_ module.load(f, **pickle_load_args)
_ pickle.UnpicklingError: invalid load key, 'f'.

**Comment by sebszyller** [comment]
Yes, `load_location` is a string path to your model. Note, that this function takes a path to a model saved with `torch.save`, so there might be some discrepancies if you saved your model directly with `pickle`.

I'd suggest doing `torch.load` manually in an interpreter. If that works, there's a problem with how you're setting variables in the script.

Tangent: what do you mean __injected into the back door__? This repo is about a model extraction defense which, while related to backdooring, is quite different.

**Comment by xiaolinjieer** [comment]
Thank you very much for your answer.I want to use this code to check whether the model I have injected into the back door has a back door. Can this code be implemented?

**Comment by sebszyller** [comment]
So with this code, you can implement the PRADA defense from our paper ([arxiv](https://arxiv.org/abs/1805.02628)), and its purpose is to detect synthetic data extraction attacks, and not backdoors.

We aren't planning to expand this repo in any shape or form. Though PRs with end-to-end examples are welcome.

**Comment by sebszyller** [comment]
This thread seems to be out of scope of this repo.
