### ISSUE TITLE
hello，I have read your paper“PRADA: Protecting Against DNN Model Stealing Attacks” which includes a novel model extraction attack and the detecter

### ISSUE THREAD

**Issue by CAuYi15** [SSGAalto/prada-protecting-against-dnn-model-stealing-attacks#3]
I found that you just release the part of the detector of the model extraction attacks, may I have the part of code of the novel model attack？Thanks a looooot!

**Comment by sebszyller** [comment]
Hey, please send us an email (institutional addresses found in the paper).

**Comment by CAuYi15** [comment]
I send to xxxx@aalto.fi ,but failed. Did I have the wrong domain name，or maybe @mail.aalto.fi?

**Comment by CAuYi15** [comment]
> Hey, please send us an email (institutional addresses found in the paper).
I send to [xxxx@aalto.fi](mailto:xxxx@aalto.fi) ,but failed. Did I have the wrong domain name，or maybe @mail.aalto.fi?

**Comment by CAuYi15** [comment]
> Hey, please send us an email (institutional addresses found in the paper).

Actually I tried the @mail.aalto.fi, but the Mail delivery also failed. Sorry to disturb you again.
